set -g history-limit 500000
set -sg escape-time 0
set-option -g repeat-time 200
set-window-option -g monitor-activity on
set -g visual-activity on

# Some tweaks to the status line
set-option -g status-position top
set -g status-right "%H:%M"
set -g window-status-format "#I:#W#{?monitor-activity,[M],}#{window_flags}"
set -g window-status-current-format "#I:#W#{?monitor-activity,[M],}#{window_flags}"
set-window-option -g window-status-current-style bg=#005f87,fg=white,bold

# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX}
set -g status-bg red
%endif

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-features ",xterm*:RGB"

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"

# Turn the mouse on
set -g mouse on

# Make copying and pasting easier
setw -g mode-keys vi
bind P paste-buffer
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Key bindings to make navigating a little easier
bind-key -n -r C-k select-pane -U
bind-key -n -r C-j select-pane -D
bind-key -n -r C-h select-pane -L
bind-key -n -r C-l select-pane -R
bind-key -n -r C-n next-window
bind-key -n -r C-p previous-window

# Make resizing easier
bind-key -r H resize-pane -L 2
bind-key -r J resize-pane -D 2
bind-key -r K resize-pane -U 2
bind-key -r L resize-pane -R 2

# Keys to toggle monitoring activity in a window
bind m set monitor-activity
# Keyt to the synchronize-panes
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

# Some extra key bindings to select higher numbered windows
bind F1 selectw -t:10
bind F2 selectw -t:11
bind F3 selectw -t:12
bind F4 selectw -t:13
bind F5 selectw -t:14
bind F6 selectw -t:15
bind F7 selectw -t:16
bind F8 selectw -t:17
bind F9 selectw -t:18
bind F10 selectw -t:19
bind F11 selectw -t:20
bind F12 selectw -t:21

bind-key M display-menu -T " Quick Actions " -x C -y C \
    "Swap Up (<Prefix> + {)"    k "swap-pane -U" \
    "Swap Down (<Prefix> + })"  j "swap-pane -D" \
    "Swap Left"  h "swap-pane -d -t '{left-of}'" \
    "Swap Right" l "swap-pane -d -t '{right-of}'" \
    ""              "" "" \
    "Kill Current Window"  k "kill-window" \
    "Kill Session"         X "kill-session"
