# Load homebrew magic
eval "$(/opt/homebrew/bin/brew shellenv zsh)"

# Set fpath
# Commented out - managed through brew for most installed apps
#fpath=($HOME/.config/zsh/completions/ $fpath)


# Enable colors and change prompt:
autoload -U colors && colors

# Prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr ' %F{red}*%f'
zstyle ':vcs_info:*' stagedstr ' %F{green}+%f'
zstyle ':vcs_info:git:*' formats '(%b%f%u%c): '
zstyle ':vcs_info:git:*' actionformats '(%b|%a%f%u%c): '

setopt PROMPT_SUBST;
PS1='%B%F{green}%n%f@%F{yellow}%m%f:%F{cyan}%~ %F{magenta}[%*]%f$ ${vcs_info_msg_0_}'

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$HOME/.cache/zsh/history
setopt appendhistory     #Append history to the history file (no overwriting)
setopt incappendhistory  #Immediately append to the history file, not just when a term is killed


# Basic auto/tab complete:
## don't cache completions
autoload -U compinit
zstyle ':completion:*' menu select
zstyle ":completion:*:commands" rehash 1
zmodload zsh/complist
compinit -u
_comp_options+=(globdots) # Include hidden files.
compdef _gnu_generic ag
# Fix Make completions
zstyle ':completion:*:*:make:*' tag-order 'targets'

export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

export MANPATH=$HOME/Root/share/man:$MANPATH
export GOROOT=$HOME/Root/src/go
export GOPATH=$HOME/Projects/gopath
export GOBIN=$GOPATH/bin
path=(
    $HOME/Root/bin
    $GOBIN
    $GOROOT/bin
    $path
)


# Aliases and Keybindings
alias getip='curl https://checkip.amazonaws.com/'
alias gad='git add'
alias gcm='git commit'
alias gco='git checkout'
alias gdi='git diff'
alias gdc='git diff --cached'
alias glg='git log'
alias gst='git status'
alias gps='git push'
alias gpl='git pull'
alias grep="grep --color"
alias ls='ls -G'
alias ll='ls -Glah'
export CLICOLOR=1
export EXA_COLORS="*.zip=1;35:*.tar.*=1;35"
alias lx='eza -lagF'
alias nless='less -NR'
alias o='/usr/bin/open'
alias psg='ps aux | grep -i'

#alias tmux="tmux -2u"
bindkey "^R" history-incremental-search-backward
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
bindkey '\e.' insert-last-word
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey "\e[3~" delete-char
bindkey -M menuselect '^[[Z' reverse-menu-complete
backward-kill-dir () {
    local WORDCHARS=${WORDCHARS/\/}
    zle backward-kill-word
}
zle -N backward-kill-dir
bindkey '^w' backward-kill-dir

# Load FZF
source <(fzf --zsh)

# Load nvm
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


export LC_ALL=en_US.UTF-8

function wiz {
	knownBulbs="l1 o1 b1"
	if [[ $1 == "list" ]]
	then
		echo "$knownBulbs"
		return
	elif [[ $1 == "scan" ]]
	then
		echo '{"method":"getPilot","params":{}}' | socat - UDP-DATAGRAM:255.255.255.255:38899,broadcast
		return
	elif [[ $1 == "l1" ]]
	then
		bulb="192.168.0.121"
	elif [[ $1 == "o1" ]]
	then
		bulb="192.168.0.122"
	elif [[ $1 == "b1" ]]
	then
		bulb="192.168.0.123"
	else
		echo "Unknown command or bulb. Known commands: 'list', 'scan'. Known bulbs: $knownBulbs"
		return
	fi

	if [[ $2 == "off" ]]
	then
		echo '{"id":1,"method":"setState","params":{"state":false}}' | nc -u -w 1 $bulb 38899
		return
        elif [[ $2 == "on" ]]
	then
		knownColours="'warm' (2700K), 'day' (4200K), 'cool' (6500K)"
		if [[ $3 == "list" ]]
		then
			echo "$knownColours"
			return
		elif [[ $3 == "warm" ]]
		then
			scene=11
		elif [[ $3 == "day" ]]
		then
			scene=12
		elif [[ $3 == "cool" ]]
		then
			scene=13
		else
			echo "Unknown color or scene. Known colors: $knownColours. Only turning on bulb (likely previous state)"
			echo '{"id":1,"method":"setState","params":{"state":true}}' | nc -u -w 1 $bulb 38899
			return
		fi
		echo '{"id":1,"method":"setPilot","params":{"sceneId":'${scene}',"dimming":100}}}' | nc -u -w 1 $bulb 38899
		return
	else
		echo "Unknown command. Known commands: 'off', 'on'"
	fi
}
